import { UserEntity } from '../entities/user.entity';

export const USER_ENTITY_FIELDS = {
  MASTER: [
    'id',
    'nickname',
    'email',
    'password',
    'status',
    'role',
    'image',
    'isArchiveUser',
    'createdAt',
    'updatedAt',
    'deletedAt',
    'lastLoginAt',
    'lastLoginIp',
    'loginAttempts',
    'products',
    'articles',
    'productComments',
    'articleComments',
    'refreshTokens',
    'productLikes',
    'articleLikes',
    'productCommentLikes',
    'articleCommentLikes',
  ] as (keyof UserEntity)[],
  YOURSELF: [
    'nickname',
    'email',
    'image',
    'createdAt',
    'products',
    'articles',
    'productComments',
    'articleComments',
  ] as (keyof UserEntity)[],
  USER: ['nickname', 'email', 'image', 'createdAt'] as (keyof UserEntity)[],
};
