export const USERS_SELECT_MASTER = {
  id: true,
  nickname: true,
  email: true,
  password: true,
  image: true,
  status: true,
  role: true,
  isArchiveUser: true,
  createdAt: true,
  updatedAt: true,
  deletedAt: true,
  lastLoginAt: true,
  lastLoginIp: true,
  loginAttempts: true,
  products: true,
  articles: true,
  productComments: true,
  articleComments: true,
  refreshToken: true,
  productLikes: true,
  articleLikes: true,
  commentLikes: true,
};

export const USERS_SELECT_OWNER = {
  id: true,
  nickname: true,
  email: true,
  password: true,
  image: true,
  status: true,
  role: true,
  createdAt: true,
  updatedAt: true,
  lastLoginAt: true,
  products: true,
  articles: true,
  productComments: true,
  articleComments: true,
  productLikes: true,
  articleLikes: true,
  commentLikes: true,
};

export const USERS_SELECT_USER = {
  nickname: true,
  email: true,
  image: true,
  createdAt: true,
};
