server {
    listen 80;
    server_name messagoom.online www.messagoom.online deploy.messagoom.online;

    location /.well-known/acme-challenge/ {
        root /usr/share/nginx/html;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}